# Generated by Django 4.0.5 on 2023-06-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('ECE', 'Electronics'), ('MECH', 'Mechanical'), ('SM', 'Smart Manufacturing'), ('DS', 'Design')], max_length=4, null=True),
        ),
    ]
