# Generated by Django 4.0.5 on 2023-06-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='branch',
        ),
    ]
