# Generated by Django 4.2.1 on 2023-06-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_batch_remove_customuser_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='batch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('ECE', 'Electronics'), ('MECH', 'Mechanical'), ('SM', 'Smart Manufacturing'), ('DS', 'Design')], max_length=4, null=True),
        ),
    ]
