# Generated by Django 4.2.1 on 2023-06-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='branch',
            new_name='user_branch',
        ),
    ]
