version: '3.8'
services:
  web:
    container_name: mavenbackend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mavenbackend
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: 'db'
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mavendb
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    expose:
      - "5432"

volumes:
  postgres_data:
