# Generated by Django 4.2.1 on 2023-08-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfoundmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
