# Generated by Django 4.2.1 on 2023-08-16 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lostandfound', '0002_alter_lostandfoundmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfoundmodel',
            name='contacts',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
