# Generated by Django 4.2.1 on 2023-08-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin',
        ),
    ]
