# Generated by Django 4.2.1 on 2023-08-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_group_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionissuemessage',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
