# Generated by Django 4.2.1 on 2023-08-23 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0006_permissionissuemessage_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('users_attended', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
